export const GET_SHORTEN_URL = 'GET_SHORTEN_URL';
export const GET_ANALYTICS = 'GET_ANALYTICS';
export const CLEAR_SHORTEN_URL = 'CLEAR_SHORTEN_URL';
export const CLEAR_ANALYTICS = 'CLEAR_ANALYTICS';
export const CLEAR_SHORTENURL_ERRORS = 'CLEAR_SHORTENURL_ERRORS,';
export const CLEAR_ANALYTICS_ERRORS = 'CLEAR_ANALYTICS_ERRORS,';
export const SHORTEN_URL_ERROR = 'SHORTEN_URL_ERROR';
export const ANALYTICS_ERROR = 'ANALYTICS_ERROR';
